apiVersion: apps/v1
kind: Deployment
metadata:
    name: myweb-deploy
spec:
    replicas: 3
    selector:
       matchLabels:
          env: production
#       matchExpressions: 
#        - { key: env, operator: In, values: [production]}
    template:
       metadata:
        name: myweb-pod
        labels:
          env: production
       spec:
        containers:
          - name: myweb-con
            image: 208011/webserver-php:v1
            ports:
            - containerPort: 80
            volumeMounts:
            - name: web
              mountPath: /var/www/html   
        volumes:
        - name: web-pvc1
          persistentVolumeClaim:
            claimName: web-pvc1

