apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: web-pvc1
   labels: 
     name: web-pvc1
spec:
   accessModes:
    - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
